name: Build and deploy the Parachain Implementers Guide to Github Pages

on:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
    - '.github/workflows/implementers_guide.yml'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Clone polkadot repo
      uses: actions/checkout@v2
      with:
        repository: paritytech/polkadot

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Setup mdBook lincheck and mermaid
      run: |
        cargo install mdbook-linkcheck mdbook-mermaid

    - name: Setup mdBook graphviz
      run: |
        sudo apt install -y graphviz
        cargo install --git https://github.com/dylanowen/mdbook-graphviz

    - name: Build implementers guide
      run: |
        mdbook build roadmap/implementers-guide/

    - name: Deploy implementers guide
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: roadmap/implementers-guide/book/html/

